-- blue 3
-- yellow 4
-- red 1
-- black 2
-- green 5


insert into tr.trails (id, colour_id, first_point_id, last_point_id, first_to_last_time, last_to_first_time) values 
	(1, 1, (select id from tr.places where name = 'Małołączniak'), (select id from tr.places where name = 'Kopa Kondracka'), 35, 45),
	(2, 1, (select id from tr.places where name = 'Kopa Kondracka'), (select id from tr.places where name = 'Przełęcz pod Kopą Kondracką'), 20, 30),
	(3, 1, (select id from tr.places where name = 'Przełęcz pod Kopą Kondracką'), (select id from tr.places where name = 'Kasprowy Wierch'), 95, 100),
	(4, 1, (select id from tr.places where name = 'Kasprowy Wierch'), (select id from tr.places where name = 'Przełęcz Liliowe'), 25, 25),
	(5, 1, (select id from tr.places where name = 'Przełęcz Liliowe'), (select id from tr.places where name = 'Przełęcz Świnicka'), 30, 25),
	(6, 1, (select id from tr.places where name = 'Przełęcz Świnicka'), (select id from tr.places where name = 'Świnica'), 60,45),
	(7, 1, (select id from tr.places where name = 'Świnica'), (select id from tr.places where name = 'Zawrat'),  45, 60),
	(8, 1, (select id from tr.places where name = 'Zawrat'), (select id from tr.places where name = 'Kozia Przełęcz'), 110, null), 
	(9, 1, (select id from tr.places where name = 'Kozia Przełęcz'), (select id from tr.places where name = 'Kozi Wierch'), 90, null),
	(10, 1, (select id from tr.places where name = 'Kozi Wierch'), (select id from tr.places where name = 'Żleb Kulczyńskiego'), 60, 45),
	(11, 1, (select id from tr.places where name = 'Żleb Kulczyńskiego'),(select id from tr.places where name = 'Zadni Granat'), 25, 25),
	(12, 1, (select id from tr.places where name = 'Zadni Granat'),(select id from tr.places where name = 'Skrajny Granat'), 25, 25),
	(13, 1, (select id from tr.places where name = 'Skrajny Granat'),(select id from tr.places where name = 'Krzyżne'), 25, 25),
	(30, 1, (select id from tr.places where name = 'Parking Dolina Strążyska'), (select id from tr.places where name = 'Polana Strążyska'), 40, 35),
	(31, 1, (select id from tr.places where name = 'Polana Strążyska'), (select id from tr.places where name = 'Przełęcz w Grzybowcu'), 40, 35),
	(32, 1, (select id from tr.places where name = 'Przełęcz w Grzybowcu'), (select id from tr.places where name = 'Wyżnia Przełęcz Kondracka'), 105, 80),
	(14, 2, (select id from tr.places where name = 'Żleb Kulczyńskiego'), (select id from tr.places where name = 'Kozia Dolinka'), 30, 45),
	(21, 2, (select id from tr.places where name = 'Odejście na Kozi Wierch'), (select id from tr.places where name = 'Kozi Wierch'), 95, 60),
	(22, 2, (select id from tr.places where name = 'Rzeżuchy'), (select id from tr.places where name = 'Dolina Pięciu Stawów'), 40, 25),
	(23, 2, (select id from tr.places where name = 'Czarny Staw Gąsienicowy'), (select id from tr.places where name = 'Karb'), 40, 30),
	(24, 2, (select id from tr.places where name = 'Karb'), (select id from tr.places where name = 'Kościelec'), 50, 50),
	(47, 2, (select id from tr.places where name = 'Parking Brzeziny'), (select id from tr.places where name = 'Psia Trawka'), 50, 40),
	(15, 5,(select id from tr.places where name = 'Nad Zmarzłym Stawem'), (select id from tr.places where name = 'Kozia Dolinka'), 10, 10),
	(16, 5,(select id from tr.places where name = 'Kozia Dolinka'), (select id from tr.places where name = 'Zadni Granat'), 50, 35),
	(26, 5,(select id from tr.places where name = 'Dwoiśniak'), (select id from tr.places where name = 'Przełęcz Liliowe'), 50, 35),
	(33, 5, (select id from tr.places where name = 'Wylot za Bramką'), (select id from tr.places where name = 'Dolina za Bramką'), 20, 20),
	(34, 5, (select id from tr.places where name = 'Polana Strążyska'), (select id from tr.places where name = 'Siklawica'), 10, 10),
	(38, 5, (select id from tr.places where name = 'Schronisko na Hali Kondratowej'), (select id from tr.places where name = 'Przełęcz pod Kopą Kondracką'), 105, 70),
	(17, 4, (select id from tr.places where name = 'Odejście na Kozią Przełęcz'), (select id from tr.places where name = 'Kozia Przełęcz'), 90, 60),
	(18, 4, (select id from tr.places where name = 'Zmarzły Staw'), (select id from tr.places where name = 'Nad Zmarzłym Stawem'), 10, 10),
	(19, 4, (select id from tr.places where name = 'Nad Zmarzłym Stawem'), (select id from tr.places where name = 'Kozia Przełęcz'), 50, 40),
	(20, 4, (select id from tr.places where name = 'Odejście na Skrajny Granat'), (select id from tr.places where name = 'Skrajny Granat'), 100, 75),
	(27, 4, (select id from tr.places where name = 'Pustelnia św. Brata Alberta'), (select id from tr.places where name = 'Klasztor Albertynów'), 10, 10),
	(28, 4, (select id from tr.places where name = 'Dolina Białego'), (select id from tr.places where name = 'Polana Białego'), 70, 55),
	(35, 4, (select id from tr.places where name = 'Dolina Małej Łąki'), (select id from tr.places where name = 'Rówienki'), 20, 15),
	(36, 4, (select id from tr.places where name = 'Rówienki'), (select id from tr.places where name = 'Przełęcz Kondracka'), 20, 15),
	(37, 4, (select id from tr.places where name = 'Przełęcz Kondracka'), (select id from tr.places where name = 'Kopa Kondracka'), 45, 30),
	(25, 3, (select id from tr.places where name = 'Zielony Staw Gąsienicowy'), (select id from tr.places where name = 'Karb'), 30, 20),
	(29, 3, (select id from tr.places where name = 'Dolina ku Dziurze'), (select id from tr.places where name = 'Jaskinia Dziura'), 20, 15),
	(39, 3, (select id from tr.places where name = 'Kuźnice'), (select id from tr.places where name = 'Pustelnia św. Brata Alberta'), 15, 10),
	(40, 3, (select id from tr.places where name = 'Pustelnia św. Brata Alberta'), (select id from tr.places where name = 'Polana Kalatówki'), 25, 20),
	(41, 3, (select id from tr.places where name = 'Pustelnia św. Brata Alberta'), (select id from tr.places where name = 'Polana Kalatówki'), 10, 10),
	(42, 3, (select id from tr.places where name = 'Polana Kalatówki'), (select id from tr.places where name = 'Schronisko na Hali Kondratowej'), 45, 35),
	(43, 3, (select id from tr.places where name = 'Schronisko na Hali Kondratowej'), (select id from tr.places where name = 'Przełęcz Kondracka'), 80, 60),
	(44, 3, (select id from tr.places where name = 'Przełęcz Kondracka'), (select id from tr.places where name = 'Wyżnia Przełęcz Kondracka'), 10, 10),
	(45, 3, (select id from tr.places where name = 'Wyżnia Przełęcz Kondracka'), (select id from tr.places where name = 'Giewont'), 15, null),
	(46, 3, (select id from tr.places where name = 'Giewont'), (select id from tr.places where name = 'Wyżnia Przełęcz Kondracka'), 10, null),
	(48, 2, (select id from tr.places where name = 'Psia Trawka'), (select id from tr.places where name = 'Schronisko Murowaniec, Hala Gąsienicowa'), 105, 80),
(49, 2, (select id from tr.places where name = 'Nad Murowańcem'), (select id from tr.places where name = 'Gąsienicowa kolejka krzesełkowa'), 35, 25),
(50, 2, (select id from tr.places where name = 'Gąsienicowa kolejka krzesełkowa'), (select id from tr.places where name = 'Zielony Staw Gąsienicowy'), 45, 30),
(51, 2, (select id from tr.places where name = 'Zielony Staw Gąsienicowy'), (select id from tr.places where name = 'Przełęcz Świnicka'), 50, 35),
(52, 1, (select id from tr.places where name = 'Parking Palenica Białczańska'), (select id from tr.places where name = 'Las pod Wołoszynem'), 45, 35),
(53, 1, (select id from tr.places where name = 'Las pod Wołoszynem'), (select id from tr.places where name = 'Wodogrzmoty Mickiewicza'), 5, 5),
(54, 1, (select id from tr.places where name = 'Wodogrzmoty Mickiewicza'), (select id from tr.places where name = 'Żabie Oko'), 90, 70),
(55, 3, (select id from tr.places where name = 'Żabie Oko'), (select id from tr.places where name = 'Schronisko Morskie Oko'), 5, 5),
(56, 1, (select id from tr.places where name = 'Schronisko Morskie Oko'), (select id from tr.places where name = 'Szeroki Piarg'), 20, 20),
(57, 1, (select id from tr.places where name = 'Schronisko Morskie Oko'), (select id from tr.places where name = 'Szeroki Piarg'), 30, 30),
(58, 1, (select id from tr.places where name = 'Szeroki Piarg'), (select id from tr.places where name = 'Czarny Staw pod Rysami'), 30, 20),
(59, 1, (select id from tr.places where name = 'Czarny Staw pod Rysami'), (select id from tr.places where name = 'Rysy'), 190, 155),
(60, 5, (select id from tr.places where name = 'Czarny Staw pod Rysami'), (select id from tr.places where name = 'Przełęcz pod Chłopkiem'), 165, 130),
(61, 4, (select id from tr.places where name = 'Schronisko Morskie Oko'), (select id from tr.places where name = 'Płaśń pod Mnichem'), 75, 60),
(62, 1, (select id from tr.places where name = 'Płaśń pod Mnichem'), (select id from tr.places where name = 'Wrota Chałubińskiego'), 55, 40),
(63, 4, (select id from tr.places where name = 'Płaśń pod Mnichem'), (select id from tr.places where name = 'Szpiglasowa Przełęcz'), 60, 45),
(64, 4, (select id from tr.places where name = 'Szpiglasowa Przełęcz'), (select id from tr.places where name = 'Szpiglasowy Wierch'), 15, 10),
(65, 4, (select id from tr.places where name = 'Odejście na Szpiglasową Przełęcz'), (select id from tr.places where name = 'Szpiglasowa Przełęcz'), 95, 75),
(66, 5, (select id from tr.places where name = 'Wodogrzmoty Mickiewicza'), (select id from tr.places where name = 'Schronisko w Roztoce'), 10, 15),
(67, 5, (select id from tr.places where name = 'Wodogrzmoty Mickiewicza'), (select id from tr.places where name = 'Rzeżuchy'), 85, 65),
(68, 5, (select id from tr.places where name = 'Rzeżuchy'), (select id from tr.places where name = 'Wielki Staw'), 45, 30),
(69, 3, (select id from tr.places where name = 'Wielki Staw'), (select id from tr.places where name = 'Odejście na Krzyżne'), 5, 5),
(70, 5, (select id from tr.places where name = 'Kuźnice'), (select id from tr.places where name = 'Myślenickie Turnie'), 75, 55),
(71, 5, (select id from tr.places where name = 'Myślenickie Turnie'), (select id from tr.places where name = 'Kasprowy Wierch'), 120, 85),
(72, 4, (select id from tr.places where name = 'Kuźnice'), (select id from tr.places where name = 'Przełęcz między Kopami'), 80, 55),
(73, 3, (select id from tr.places where name = 'Kuźnice'), (select id from tr.places where name = 'Odejście na Nosalową Przełęcz'), 15, 10),
(74, 3, (select id from tr.places where name = 'Odejście na Nosalową Przełęcz'), (select id from tr.places where name = 'Przełęcz między Kopami'), 70, 45),
(75, 5, (select id from tr.places where name = 'Odejście na Nosalową Przełęcz'), (select id from tr.places where name = 'Nosalowa Przełęcz'), 20, 15),
(76, 5, (select id from tr.places where name = 'Nosalowa Przełęcz'), (select id from tr.places where name = 'Nosal'), 15, 10),
(77, 5, (select id from tr.places where name = 'Murowanica'), (select id from tr.places where name = 'Nosal'), 55, 45),
(78, 5, (select id from tr.places where name = 'Parking Jaszczurówka'), (select id from tr.places where name = 'Olczyska Polana'), 45, 30),
(79, 4, (select id from tr.places where name = 'Olczyska Polana'), (select id from tr.places where name = 'Nosalowa Przełęcz'), 30, 20),
(80, 5, (select id from tr.places where name = 'Olczyska Polana'), (select id from tr.places where name = 'Polana Kopieniec'), 40, 30),
(81, 5, (select id from tr.places where name = 'Polana Kopieniec'), (select id from tr.places where name = 'Wielki Kopieniec'), 15, 10),
(82, 5, (select id from tr.places where name = 'Wielki Kopieniec'), (select id from tr.places where name = 'Krzyż pod Kopieńcem'), 15, 15),
(83, 5, (select id from tr.places where name = 'Polana Kopieniec'), (select id from tr.places where name = 'Krzyż pod Kopieńcem'), 20, 20),
(85, 1, (select id from tr.places where name = 'Parking Toporowa Cyrhla'), (select id from tr.places where name = 'Odejście na Psią Trawkę'), 30, 20),
(86, 5, (select id from tr.places where name = 'Odejście na Psią Trawkę'), (select id from tr.places where name = 'Krzyż pod Kopieńcem'), 15, 15),
(87, 1, (select id from tr.places where name = 'Odejście na Psią Trawkę'), (select id from tr.places where name = 'Psia Trawka'), 40, 35),
(88, 1, (select id from tr.places where name = 'Las pod Wołoszynem'), (select id from tr.places where name = 'Polana pod Wołoszynem'), 45, 35),
(89, 1, (select id from tr.places where name = 'Polana pod Wołoszynem'), (select id from tr.places where name = 'Rowień Waksmundzka'), 55, 45),
(90, 1, (select id from tr.places where name = 'Rowień Waksmundzka'), (select id from tr.places where name = 'Psia Trawka'), 45, 60),
(91, 5, (select id from tr.places where name = 'Rowień Waksmundzka'), (select id from tr.places where name = 'Gęsia Szyja'), 25, 20),
(92, 5, (select id from tr.places where name = 'Rusinowa Polana'), (select id from tr.places where name = 'Gęsia Szyja'), 35, 25),
(93, 2, (select id from tr.places where name = 'Polana pod Wołoszynem'), (select id from tr.places where name = 'Czerwone Brzeżki'), 30, 30),
(94, 3, (select id from tr.places where name = 'Parking Palenica Białczańska'), (select id from tr.places where name = 'Czerwone Brzeżki'), 45, 35),
(95, 3, (select id from tr.places where name = 'Czerwone Brzeżki'), (select id from tr.places where name = 'Rusinowa Polana'), 10, 10),
(96, 5, (select id from tr.places where name = 'Parking Wierch Poroniec'), (select id from tr.places where name = 'Rusinowa Polana'), 60, 50),
(97, 3, (select id from tr.places where name = 'Parking Zazadnia'), (select id from tr.places where name = 'Rusinowa Polana'), 80, 55),
(98, 5, (select id from tr.places where name = 'Rowień Waksmundzka'), (select id from tr.places where name = 'Wolarczyska'), 60, 50),
(99, 5, (select id from tr.places where name = 'Wolarczyska'), (select id from tr.places where name = 'Las Gąsienicowy'), 55, 65),
(101, 2, (select id from tr.places where name = 'Wolarczyska'), (select id from tr.places where name = 'Dolina Pańszczyca'), 25, 20),
(102, 4, (select id from tr.places where name = 'Dolina Pańszczyca'), (select id from tr.places where name = 'Krzyżne'), 115, 85),
(103, 4, (select id from tr.places where name = 'Dolina Pańszczyca'), (select id from tr.places where name = 'Las Gąsienicowy'), 45, 55),
(104, 4, (select id from tr.places where name = 'Las Gąsienicowy'), (select id from tr.places where name = 'Schronisko Murowaniec, Hala Gąsienicowa'), 5, 5),
(105, 4, (select id from tr.places where name = 'Odejście na Krzyżne'), (select id from tr.places where name = 'Krzyżne'), 115, 75),
(106, 3, (select id from tr.places where name = 'Żabie Oko'), (select id from tr.places where name = 'Dolina Pięciu Stawów'), 110, 100),
(107, 3, (select id from tr.places where name = 'Dolina Pięciu Stawów'), (select id from tr.places where name = 'Wielki Staw'), 5, 5),
(108, 3, (select id from tr.places where name = 'Wielki Staw'), (select id from tr.places where name = 'Odejście na Krzyżne'), 5, 5),
(109, 3, (select id from tr.places where name = 'Odejście na Krzyżne'), (select id from tr.places where name = 'Odejście na Kozi Wierch'), 10, 10),
(110, 3, (select id from tr.places where name = 'Odejście na Kozi Wierch'), (select id from tr.places where name = 'Odejście na Szpiglasową Przełęcz'), 5, 5),
(111, 3, (select id from tr.places where name = 'Odejście na Szpiglasową Przełęcz'), (select id from tr.places where name = 'Odejście na Kozią Przełęcz'), 5, 5),
(112, 3, (select id from tr.places where name = 'Odejście na Kozią Przełęcz'), (select id from tr.places where name = 'Zawrat'), 75, 55),
(113, 3, (select id from tr.places where name = 'Zmarzły Staw'), (select id from tr.places where name = 'Zawrat'), 70, 50),
(114, 3, (select id from tr.places where name = 'Odejście na Skrajny Granat'), (select id from tr.places where name = 'Zmarzły Staw'), 20, 20),
(115, 3, (select id from tr.places where name = 'Czarny Staw Gąsienicowy'), (select id from tr.places where name = 'Odejście na Skrajny Granat'), 15, 15),
(116, 2, (select id from tr.places where name = 'Parking Łysa Polana'), (select id from tr.places where name = 'Parking Palenica Białczańska'), 20, 20),
(118, 3, (select id from tr.places where name = 'Parking Łysa Polana'), (select id from tr.places where name = 'Pod Wielickim Szczytem'), 310, 255),
(119, 5, (select id from tr.places where name = 'Pod Wielickim Szczytem'), (select id from tr.places where name = 'Polski Grzebień'), 20, 15),
(120, 4, (select id from tr.places where name = 'Polski Grzebień'), (select id from tr.places where name = 'Mała Wysoka'), 50, 35),
(121, 5, (select id from tr.places where name = 'Śląski Dom'), (select id from tr.places where name = 'Polski Grzebień'), 170, 130),
(122, 3, (select id from tr.places where name = 'Pod Wielickim Szczytem'), (select id from tr.places where name = 'Rohatka'), 60, 40),
(123, 3, (select id from tr.places where name = 'Zbójnicka Chata'), (select id from tr.places where name = 'Rohatka'), 100, 75),
(124, 5, (select id from tr.places where name = 'Gąsienicowa kolejka krzesełkowa'), (select id from tr.places where name = 'Dwoiśniak'), 10, 10),
(125, 4, (select id from tr.places where name = 'Dwoiśniak'), (select id from tr.places where name = 'Kasprowy Wierch'), 60, 40);