spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: tr
  datasource:
#    url: postgres://qdkvxfcfvkhdbg:058ec3f708407536888603e4c72c37f807ce71d4b194e620ff044312676b7e1b@ec2-23-23-237-68.compute-1.amazonaws.com:5432/d8hptv2stdtrka
    url: jdbc:postgresql://localhost:5432/turysta
    username: tr_admin
    password: admin1
    driver-class-name: org.postgresql.Driver

flyway:
  schemas: tr
  validate-on-migrate: false

server:
  context-path: /api
  port: 8070

security:
  user:
    password: admin1

